builds:
  -
    main: ./cmd/engine/main.go
    env:
    - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: battlesnakeio
    name: engine
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
