env:
  global:
  - CC_TEST_REPORTER_ID=7270ff0025c47f5c76e29b2e422f2c99615339a5abcfe0d31074b7818edf4054
  - secure: WtBOVy1ZxzY8OJYwIdJA+MlS28fE1/oIEC0T5DS46ItYfpOJGaYjqXXF9lfuwherlh/INI288/B4g/C7NTkwL+bqAflLeHQZmtPoK/m6DWuYppQU0T2nIu+TKTikAfnQ9Pt7zCrWukox/I1eNb+FIMUjLFY4eDKSat81A/DiBX1aoXMUeCgagTQJkPYza8mw7K49VoeRBxGuitO/y5jq4hghLsv1M++aUcr3iaVvTikALTHuLWlPu7VMHXu+AKfSglFFaheIv3FaykXVoeB6AQgpAncT3N37/lNvgrMcVBN2tRQe5YhiF4XgZdRXqW4z+cM8MooQ4zDCaklCkzftRdhcne2KDC75HksyxFhx6v/7sYHZl066GwzqNcOEO23uAUx/w5thrsLBA1dDGfW4juzGPfWvNJwEjdkDWezwHIEjgkUp209UMvvP9pGAQYSSqFRx8ri5CO/P1gUa27hH7/yQAHAQYQHoNBQyIvRzmn9Ii2z3owDnzmwIcSNKz+XVf5hot+bIS+f5n1UZWsF7Wt//RcL120Q7UIiX47i47XZ56cO3xSxnz8XMoyQNcOF1hmf47zt3ax8FrjSlgp9F4jyFILxwyd3VSnGq+Xh0Y7X9unlm/QKk9Wvk3JdtL/VBRZ6ujqHvtq9IzvUvy9D2ZCa2/s5bmQLC313Okjy3fto=
language: go
go:
- 1.10.2
go_import_path: github.com/battlesnakeio/engine
services:
- docker
stages:
- lint
- test
- name: deploy
  if: tag IS present
jobs:
  include:
  - stage: lint
    script:
    - go get -u github.com/alecthomas/gometalinter
    - gometalinter --install
    - make lint
  - stage: test
    script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    - docker run -d --name=battlesnake-redis --rm -t -p 6379:6379 redis
    - REDIS_URL=redis://127.0.0.1:6379 make test
    - cp coverage.txt c.out
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
    - bash <(curl -s https://codecov.io/bash)
    - docker rm -f battlesnake-redis
    - rm ./cc-test-reporter
  - script: make test-e2e
  - stage: deploy
    script: skip
    deploy:
    - provider: script
      skip_cleanup: true
      script: curl -sL https://git.io/goreleaser | bash
      on:
        tags: true
